name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          role-session-name: GitHubActions
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Initialize Terraform
        working-directory: infra
        run: terraform init

      - name: Apply Terraform Configuration
        working-directory: infra
        run: terraform apply -auto-approve

      - name: Upload Lambda Function Package
        run: |
          aws lambda update-function-code \
            --function-name AggregationFunction \
            --zip-file fileb://lambda_function.zip \
            --region ap-northeast-1
