name: Test Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install unittest2 boto3

      - name: Run Unit Tests
        run: |
          chmod +x scripts/unit_test.sh
          ./scripts/unit_test.sh

      - name: Run End-to-End Tests
        run: |
          python -m unittest discover -s tests/e2e -p 'test_*.py'
